### ISSUE TITLE
`AreFileApisANSI()` unavailable under Windows UWP

### ISSUE THREAD

**Issue by nickelpro** [soasis/idk#3]
Used here: https://github.com/soasis/idk/blob/6173bb3d433a3dab65e8c356ef69441aa5a86275/include/ztd/idk/detail/windows.hpp#L77

No idea if Windows UWP is a platform ya'll care about, but right now that's the only target unavailable for vcpkg because of the issue title.

**Comment by ThePhD** [comment]
Ah, okay. I'll try to transition this out to something else.

**Comment by ThePhD** [comment]
This should be (?) taken care of, I hope.
